package uk.bharatha.schedulingApp;

import javax.swing.JOptionPane;

public class AddPersonDialog extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form AddPersonDialog
	 * 
	 * @param parent
	 * @param modal
	 */
	public AddPersonDialog(java.awt.Frame parent, boolean modal) {
		super(parent, true);
		initComponents();
	}

	/**
	 * Checks form validity
	 * 
	 * @return
	 */
	private boolean isInputValid() {
		if (firstNameField.getText().equals("") || lastNameField.getText().equals("")
				|| emailField.getText().equals("")) {
			showInvalidInputDialog();
			return false;
		}
		if (!emailField.getText().contains("@")) {
			showInvalidEmailFormat();
			return false;
		}
		for (Person pers : DataManager.getPersons()) {
			if (pers.getemail().toLowerCase().equals(emailField.getText().toLowerCase())) {
				showDuplicateEmailError();
				return false;
			}
		}
		return true;
	}

	/**
	 * Shows dialog for invalid phone input
	 */
	private void showDuplicateEmailError() {
		JOptionPane.showMessageDialog(this, "Email already exists. ", "Error",
				JOptionPane.WARNING_MESSAGE);
	}

	/**
	 * Shows dialog for invalid phone input
	 */
	private void showInvalidEmailFormat() {
		JOptionPane.showMessageDialog(this, "Invalid email foramt..", "Phone Format", JOptionPane.WARNING_MESSAGE);
	}

	/**
	 * Shows dialog for invalid input
	 */
	private void showInvalidInputDialog() {
		JOptionPane.showMessageDialog(this, "Invalid input. Please fill all fields.", "Add Person",
				JOptionPane.WARNING_MESSAGE);
	}

	/**
	 * Creates a person using form input
	 * 
	 * @return
	 */
	private boolean createPerson() {
		String firstName = firstNameField.getText();
		String lastName = lastNameField.getText();
		String emailID = emailField.getText();

		if (isInputValid()) {
			DataManager.addPerson(new Person(firstName, lastName, emailID));
			return true;
		}
		return false;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		firstNameField = new javax.swing.JTextField();
		lastNameField = new javax.swing.JTextField();
		emailField = new javax.swing.JFormattedTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		addButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("First:");

		jLabel2.setText("Last:");

		jLabel3.setText("Email:");

		addButton.setText("Add");
		addButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addButtonActionPerformed(evt);
			}
		});

		cancelButton.setText("Cancel");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		jLabel4.setText("Add new person");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel1).addComponent(jLabel2).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
														Short.MAX_VALUE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(emailField).addComponent(lastNameField).addComponent(firstNameField)))
						.addGroup(layout.createSequentialGroup().addGap(46, 46, 46).addComponent(jLabel4))
						.addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(addButton).addComponent(cancelButton))));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addButtonActionPerformed
		boolean success = createPerson();
		if (success)
			this.dispose();
	}// GEN-LAST:event_addButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
		this.dispose();
	}// GEN-LAST:event_cancelButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addButton;
	private javax.swing.JButton cancelButton;
	private javax.swing.JTextField firstNameField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField lastNameField;
	private javax.swing.JFormattedTextField emailField;
	// End of variables declaration//GEN-END:variables
}
